server:
  port: 8081
  ssl:
    enabled: false   # 🚫 Desactivamos HTTPS, usa HTTP

spring:
  application:
    name: bff

  datasource:
    url: jdbc:mysql://localhost:3306/backend_s5?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 0k4mysm0.23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: INFO
    cl.duoc.bff: DEBUG
