# notificaciones-service.yml
server:
  port: 8082

spring:
  application:
    name: notificaciones-service

  config:
    import: optional:configserver:
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notificaciones-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework: INFO
    cl.duoc.notificaciones: DEBUG

